export const siteConfig = {
  name: 'Just Luxury Transfers',
  shortName: 'Just Luxury',
  description: 'Premium private airport transfers, private drivers, intercity routes, and curated excursions from Marrakech across Morocco.',
  url: 'https://www.justluxurytransfers.com',
  defaultLocale: 'en',
  locales: ['en', 'fr', 'es', 'it', 'de'],
  ogImage: '/images/luxury/hero.webp',
  twitterHandle: '@justluxurytransfers',
  creator: 'Just Luxury Transfers',
  seo: {
    primaryKeyword: 'Marrakech airport transfers',
    keywords: ['Marrakech airport transfers', 'private chauffeur Marrakech', 'luxury transfers Morocco', 'Marrakech excursions', 'Morocco private driver'],
    geoKeywords: ['Marrakech', 'Atlas Mountains', 'Ourika Valley', 'Essaouira', 'Morocco'],
    audience: ['airport travellers', 'holiday makers', 'hotels and travel partners'],
    languages: ['English', 'French', 'Spanish', 'Italian', 'German'],
  },
  campaign: { leadCurrency: 'MAD' },
  business: {
    legalName: 'Just Luxury Transfers',
    category: 'Private transfer service',
    region: 'Marrakech-Safi',
    phoneDisplay: '+212 6 74 01 61 49',
    phoneInternational: '+212674016149',
    phoneTel: '+212674016149',
    email: 'contactluxurytransfers@gmail.com',
    addressDisplay: 'Marrakech, Morocco',
    city: 'Marrakech',
    postalCode: '40000',
    country: 'MA',
    latitude: 31.6295,
    longitude: -7.9811,
    hoursDisplay: '24/7 - flight tracking included',
    openingHours: 'Mo-Su 00:00-23:59',
    whatsapp: 'https://wa.me/212674016149?text=Hello%2C%20I%20would%20like%20to%20book%20a%20luxury%20transfer.',
    googleReviews: 'https://maps.app.goo.gl/BYJQWvFr7pNVw4p7A',
    googleMapsUrl: 'https://maps.google.com/?q=Marrakech,Morocco',
    instagram: 'https://www.instagram.com/justluxurytransfers/',
    facebook: 'https://www.facebook.com/',
    sameAs: ['https://www.instagram.com/justluxurytransfers/', 'https://www.facebook.com/'],
    areaServed: ['Marrakech', 'Marrakech Menara Airport', 'Ourika Valley', 'Essaouira', 'Agafay Desert', 'Morocco'],
    services: ['Marrakech airport transfers', 'Private chauffeur service', 'Intercity transfers', 'Luxury vehicle hire', 'Private Morocco excursions', '24/7 flight tracking'],
  },
};

export type SiteConfig = typeof siteConfig;
