import Image from 'next/image';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, Mail, MapPin, MessageCircle, Phone } from 'lucide-react';
import { excursions, fleet, getExcursion, getFleetItem, getRoute, routes } from './data';
import { siteConfig } from '@/config/site';

type RouteCard = { slug: string; title: string; duration: string; image: string; copy: string };

const marrakechTransfers: RouteCard[] = [
  { slug: 'agadir-airport-to-tagahzout', title: 'Marrakech Menara Airport - Medina', duration: '20 min', image: '/images/luxury/airport.webp', copy: 'Private meet and greet from arrivals to your riad, hotel, or private address.' },
  { slug: 'agadir-airport-to-agadir', title: 'Marrakech Menara Airport - Hivernage', duration: '20 min', image: '/images/luxury/hero.webp', copy: 'A direct, discreet arrival for hotels and residences in the new city.' },
  { slug: 'agadir-to-marrakech', title: 'Marrakech - Ourika Valley', duration: '1 h 15', image: '/images/luxury/paradise-valley.jpg', copy: 'A private ride into the Atlas foothills, paced around your day.' },
  { slug: 'agadir-to-essaouira', title: 'Marrakech - Essaouira', duration: '2 h 45', image: '/images/luxury/essaouira-trip.jpg', copy: 'A comfortable coastal journey with room to stop when the route asks for it.' },
  { slug: 'agadir-to-taroudant', title: 'Marrakech - Agafay Desert', duration: '45 min', image: '/images/luxury/desert-safari.jpg', copy: 'The smooth start to desert camps, sunset dinners, and private adventures.' },
  { slug: 'agadir-to-paradise-valley', title: 'Marrakech - Atlas Mountains', duration: '1 h 30', image: '/images/luxury/marrakech-trip.jpg', copy: 'A private road into dramatic landscapes, villages, and wide-open views.' },
];

const marrakechExcursions: RouteCard[] = [
  { slug: 'paradise-valley', title: 'Ourika Valley and Atlas Mountains', duration: 'Full day', image: '/images/luxury/paradise-valley.jpg', copy: 'A private day of mountain air, local lunches, and time to take it slowly.' },
  { slug: 'desert-safari', title: 'Agafay Desert Escape', duration: 'Half day', image: '/images/luxury/desert-safari.jpg', copy: 'Desert scenery, sunset light, and a comfortable way to get there.' },
  { slug: 'marrakech-day-trip', title: 'Marrakech City Day', duration: 'Full day', image: '/images/luxury/marrakech-trip.jpg', copy: 'Let a private driver keep the city day flowing from first stop to final dinner.' },
  { slug: 'essaouira-coast', title: 'Essaouira Coast', duration: 'Full day', image: '/images/luxury/essaouira-trip.jpg', copy: 'A thoughtful Atlantic escape from Marrakech, with the day kept flexible.' },
  { slug: 'taroudant-discovery', title: 'Atlas Villages and Valleys', duration: 'Full day', image: '/images/luxury/taroudant-trip.jpg', copy: 'Go beyond the city with a private route into the landscapes around Marrakech.' },
  { slug: 'quad-bike-adventure', title: 'Agafay Quad Adventure', duration: 'Half day', image: '/images/luxury/quad-bike.jpg', copy: 'Private transport for an active desert afternoon, without the logistics.' },
];

function PageHero({ locale, label, title, image }: { locale: string; label: string; title: string; image: string }) {
  return <section className="luxury-page-hero"><div className="luxury-page-hero__media"><Image src={image} alt="" fill sizes="100vw" priority /></div><div className="luxury-container"><div className="luxury-breadcrumb"><Link href={`/${locale}`}>Home</Link><span>/</span><span>{label}</span></div><span className="luxury-kicker" style={{ display: 'block', marginTop: 22 }}>{label}</span><h1>{title}</h1></div></section>;
}

function JourneyCards({ locale, kind, items }: { locale: string; kind: 'transfers' | 'fleet' | 'excursions'; items: RouteCard[] }) {
  return <div className="luxury-card-grid">{items.map((item, index) => <Link className="luxury-card" key={item.slug} href={`/${locale}/${kind}/${item.slug}`}><div className="luxury-card__image"><Image src={item.image} alt={item.title} fill sizes="(max-width: 720px) 50vw, 33vw" /></div><div className="luxury-card__body"><span className="luxury-kicker">0{index + 1} / {kind === 'transfers' ? 'Private transfer' : kind === 'excursions' ? 'Private experience' : 'Vehicle'}</span><h3>{item.title}</h3><p>{item.copy}</p><div className="luxury-card__meta"><span>{item.duration}</span><span>Explore</span></div></div><ArrowUpRight className="luxury-card__arrow" size={18} /></Link>)}</div>;
}

function InfoRail({ locale }: { locale: string }) {
  return <section className="luxury-section luxury-section--tight"><div className="luxury-container luxury-split"><div className="luxury-split__copy"><span className="luxury-kicker">Always included</span><h2>One less thing to think about.</h2><ul className="luxury-list"><li>Private door-to-door vehicle</li><li>Professional local driver</li><li>Flight tracking for Marrakech airport pickups</li><li>Flexible support by WhatsApp</li></ul><Link className="luxury-button" href={`/${locale}/book`}>Request a quote <ArrowUpRight size={15} /></Link></div><div className="luxury-split__media"><Image src="/images/luxury/mercedes-e-class.webp" alt="Executive private transfer vehicle" fill sizes="(max-width: 980px) 100vw, 50vw" /></div></div></section>;
}

export function TransferListing({ locale }: { locale: string }) {
  return <div className="luxury-shell"><PageHero locale={locale} label="Marrakech transfers" title="Every route, handled with care." image="/images/luxury/airport.webp" /><section className="luxury-section"><div className="luxury-container"><div className="luxury-section-heading"><div><span className="luxury-kicker">Private transfers from Marrakech</span><h2>From Menara Airport to the places you came to see.</h2></div><p>Airport pickups, city-to-city journeys, and private routes planned around your timing.</p></div><JourneyCards locale={locale} kind="transfers" items={marrakechTransfers} /></div></section><InfoRail locale={locale} /></div>;
}

export function FleetListing({ locale }: { locale: string }) {
  const vehicles: RouteCard[] = fleet.map((item) => ({ slug: item.slug, title: item.name, duration: item.capacity, image: item.image, copy: item.description }));
  return <div className="luxury-shell"><PageHero locale={locale} label="Fleet" title="The right vehicle for the road ahead." image="/images/luxury/fleet.webp" /><section className="luxury-section"><div className="luxury-container"><div className="luxury-section-heading"><div><span className="luxury-kicker">Our vehicles</span><h2>Comfort, space, and quiet confidence.</h2></div><p>Every vehicle is clean, maintained, air-conditioned, and ready for Marrakech and the road beyond.</p></div><JourneyCards locale={locale} kind="fleet" items={vehicles} /></div></section></div>;
}

export function ExcursionListing({ locale }: { locale: string }) {
  return <div className="luxury-shell"><PageHero locale={locale} label="Excursions" title="Morocco, from Marrakech, on your own terms." image="/images/luxury/excursions.avif" /><section className="luxury-section"><div className="luxury-container"><div className="luxury-section-heading"><div><span className="luxury-kicker">Private experiences</span><h2>Days that feel made for you.</h2></div><p>Tell us what you want to see and we will shape the timing, route, and vehicle around it.</p></div><JourneyCards locale={locale} kind="excursions" items={marrakechExcursions} /></div></section></div>;
}

function Detail({ locale, heading, label, image, copy, duration, back }: { locale: string; heading: string; label: string; image: string; copy: string; duration: string; back: string }) {
  return <div className="luxury-shell"><PageHero locale={locale} label={label} title={heading} image={image} /><section className="luxury-section"><div className="luxury-container luxury-detail"><div className="luxury-detail__image"><Image src={image} alt={heading} fill sizes="(max-width: 980px) 100vw, 60vw" /></div><div className="luxury-detail__copy"><span className="luxury-kicker">Just Luxury Transfers / Marrakech</span><h2>Travel well. Arrive ready.</h2><p>{copy}</p><div className="luxury-detail__facts"><div className="luxury-fact"><strong>{duration}</strong><span>Typical journey</span></div><div className="luxury-fact"><strong>Private</strong><span>Service type</span></div></div><ul className="luxury-list"><li>Professional driver selected for your journey</li><li>Clean, comfortable vehicle with room for your plans</li><li>Direct WhatsApp support before and during travel</li></ul><div className="luxury-hero__links"><Link className="luxury-button" href={`/${locale}/book`}>Book this journey <ArrowUpRight size={15} /></Link><Link className="luxury-button luxury-button--outline" href={`/${locale}/${back}`}><ArrowLeft size={15} /> Back to {back}</Link></div></div></div></section></div>;
}

export function TransferDetail({ locale, slug }: { locale: string; slug: string }) { const item = marrakechTransfers.find((route) => route.slug === slug) ?? marrakechTransfers[0]; return <Detail locale={locale} heading={item.title} label="Marrakech private transfer" image={item.image} copy={item.copy} duration={item.duration} back="transfers" />; }
export function FleetDetail({ locale, slug }: { locale: string; slug: string }) { const item = getFleetItem(slug) ?? fleet[0]; return <Detail locale={locale} heading={item.name} label={item.category} image={item.image} copy={item.description} duration={item.capacity} back="fleet" />; }
export function ExcursionDetail({ locale, slug }: { locale: string; slug: string }) { const item = marrakechExcursions.find((experience) => experience.slug === slug) ?? marrakechExcursions[0]; return <Detail locale={locale} heading={item.title} label="Private Marrakech excursion" image={item.image} copy={item.copy} duration={item.duration} back="excursions" />; }

export function AboutPage({ locale }: { locale: string }) { return <div className="luxury-shell"><PageHero locale={locale} label="About us" title="A better way to move through Morocco." image="/images/luxury/hero.webp" /><section className="luxury-section"><div className="luxury-container luxury-split"><div className="luxury-split__media"><Image src="/images/luxury/fleet.webp" alt="Just Luxury Transfers vehicle" fill sizes="(max-width: 980px) 100vw, 50vw" /></div><div className="luxury-split__copy"><span className="luxury-kicker">Based in Marrakech</span><h2>Built around how travel should feel.</h2><p>Just Luxury Transfers is a Marrakech-based team making airport arrivals, private drives, and Morocco excursions feel thoughtful from the first message.</p><p>We know the medina, the airport, the Atlas roads, and the small decisions that turn a transfer into a welcome.</p><Link className="luxury-button" href={`/${locale}/contact`}>Talk to the team <ArrowUpRight size={15} /></Link></div></div></section></div>; }

export function ContactPage({ locale }: { locale: string }) { return <div className="luxury-shell"><PageHero locale={locale} label="Contact" title="Let us plan the road ahead." image="/images/luxury/airport.webp" /><section className="luxury-section"><div className="luxury-container luxury-contact-grid"><div className="luxury-contact-card"><div><span className="luxury-kicker">Marrakech, Morocco</span><h2 style={{ fontSize: 'clamp(2.5rem, 5vw, 5rem)', fontWeight: 400, letterSpacing: '-.06em', lineHeight: .95, margin: '18px 0 22px' }}>A real person is ready to help.</h2></div><div className="luxury-contact-line"><span><Phone size={13} /> Phone</span><a href={`tel:${siteConfig.business.phoneTel}`}>{siteConfig.business.phoneDisplay}</a></div><div className="luxury-contact-line"><span><Mail size={13} /> Email</span><a href={`mailto:${siteConfig.business.email}`}>{siteConfig.business.email}</a></div><div className="luxury-contact-line"><span><MapPin size={13} /> Base</span><strong>Marrakech, Morocco</strong></div></div><div className="luxury-split__copy"><span className="luxury-kicker">Tell us your route</span><h2>We will shape the right journey.</h2><p>Share your arrival time, destination, group size, and any special requests. We will come back with a clear option and the right vehicle.</p><a className="luxury-button" href={siteConfig.business.whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={15} /> WhatsApp us</a></div></div></section></div>; }

export function BookPage({ locale }: { locale: string }) { return <div className="luxury-shell"><PageHero locale={locale} label="Book now" title="Your Marrakech journey starts here." image="/images/luxury/hero.webp" /><section className="luxury-section"><div className="luxury-container luxury-split"><div className="luxury-split__copy"><span className="luxury-kicker">Request a private journey</span><h2>A calm plan for every mile.</h2><p>Send your pickup, destination, date, and group size. We will confirm availability, vehicle, and price personally.</p><a className="luxury-button" href={siteConfig.business.whatsapp} target="_blank" rel="noreferrer">Request on WhatsApp <ArrowUpRight size={15} /></a></div><div className="luxury-split__media"><Image src="/images/luxury/mercedes-e-class.webp" alt="Private Marrakech transfer vehicle" fill sizes="(max-width: 980px) 100vw, 50vw" /></div></div></section></div>; }

export function PrivateDriverPage({ locale }: { locale: string }) { return <div className="luxury-shell"><PageHero locale={locale} label="Private driver" title="A driver for the day, or the whole journey." image="/images/luxury/mercedes-e-class.webp" /><section className="luxury-section"><div className="luxury-container luxury-split"><div className="luxury-split__copy"><span className="luxury-kicker">Chauffeur service in Marrakech</span><h2>Keep your day open.</h2><p>For meetings, a celebration, shopping, or a day beyond Marrakech, book a private vehicle by the hour or the day.</p><Link className="luxury-button" href={`/${locale}/contact`}>Ask about availability <ArrowUpRight size={15} /></Link></div><div className="luxury-split__media"><Image src="/images/luxury/mercedes-e-class.webp" alt="Marrakech private driver service" fill sizes="(max-width: 980px) 100vw, 50vw" /></div></div></section></div>; }
